/// Flutter icons SvqIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SvqIcon
///      fonts:
///       - asset: fonts/SvqIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SvqIcon {
  SvqIcon._();

  static const _kFontFam = 'SvqIcon';
  static const _kFontPkg = null;

  static const IconData rewards = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData svqicon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData poin = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
